# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "node1"
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "172.28.128.101"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL

    sudo apt update -y
    sudo systemctl disable systemd-networkd-wait-online.service
    sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    sudo apt update -y
    apt-cache policy docker-ce
    echo Installing Docker CE...
    sudo apt install docker-ce -y

    echo Adding user to docker group
    sudo usermod -aG docker vagrant
    echo Done

  SHELL
end
